spring.config.activate.on-profile=heroku

# Heroku config vars
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Heroku dyno port
server.port=${PORT:8080}

# quick start (auto-create/update tables)
spring.jpa.hibernate.ddl-auto=update
# after adding migrations
# spring.jpa.hibernate.ddl-auto=validate